### PR TITLE
purchases ordered by time

### PR DESCRIPTION
**Pull request by Danqi7**
Purchase view is ordered by time that the purchase was created.Added createdAt field to purchase data. Implemented in ng-repeat orderBy. Changed the firebase retrieve data method from event type "value" to event type "child_added" so that we can traverse each purchase and convert JSON to array since ng orderBy only works with array.

### CODE REVIEW

**Comment by jameswhang** [comment]
Looks good!

**Comment by jameswhang** [comment]
@jb08  Wanna take a look at Danqi's code before I merge it in?

**Comment by jb08** [comment]
working on reviewing now

**Comment by jb08** [comment]
on git... first I did _git checkout -b backlog-6_ and then _git checkout -- ._ {to remove my local changes that weren't needed}. I checked a local copy of the code and nothing seemed changed. Then I read the note on trello and did _git pull --rebase=preserve origin backlog-6_. That updated my local repo. I read the 3 files changed using iTerm & vim and they looked reasonable. I also looked at the new field createdAt of the purchases db on firebase. I tested the new feature with $10 for "Test-most recent purchase" and it was the 4th of 11 purchases. Based on my understanding of the branch, should it have been first? 

overall nice job Danqi.

**Comment by jameswhang** [comment]
@jb08 It's easier if you start with _git fetch origin backlog-6_ and then do _git checkout backlog-6_. I didn't experience that happening. Let me check more.

**Comment by jameswhang** [comment]
@jb08 I see what the issue is. Those 3 showing up at the top were remaining data before danqi added the 'createdAt' field to it, so it affected this. @Danqi7, when you add a new field to the db, blow up the existing db, or write to a different firebase url so that the outdated data don't affect your result.

**Comment by jb08** [comment]
ok got it

**Pull request merged**
